### ISSUE TITLE
Doesn't work on wasm32-unknown-unknown target

### ISSUE THREAD

**Issue by saikatdas0790** [fnichol/names#22]
This is what I'm seeing

![image](https://user-images.githubusercontent.com/7412443/188486294-4f57c009-945a-45ab-9a7b-3e7f5baa7f2f.png)

I understand that this package has internal dependencies that rely on [`getrandom`](https://crates.io/crates/getrandom/0.2.7) which doesn't support `wasm32-unknown-unknown` as documented [here](https://docs.rs/getrandom/latest/getrandom/#webassembly-support)

I am going to be running this on a blockchain that only supports the `wasm32-unknown-unknown` target. On this platform, they have APIs that provide their own source of randomness.

I was wondering if you are open to adding to the API that lets the caller pass their own source of randomness and that is then used to seed and generate the names. On the platform that I'll be deploying to, the random value looks like [this](https://internetcomputer.org/docs/current/references/ic-interface-spec#ic-raw_rand)

Thoughts?

**Comment by TheBotlyNoob** [comment]
https://docs.rs/getrandom/latest/getrandom/#webassembly-support:
> To enable the js Cargo feature, add the following to the dependencies section in your Cargo.toml file:
> ```toml
> [dependencies]
> getrandom = { version = "0.2", features = ["js"] }
> ```
> This can be done even if getrandom is not a direct dependency. Cargo allows crates to enable features for indirect dependencies.

Could you not just add that to your `Cargo.toml`?

**Comment by saikatdas0790** [comment]
I did not try this. For now, I ended up doing this functionality client side. Will try next time I need this
